Update called-required-workflow.yml

diff --git a/.github/workflows/called-required-workflow.yml b/.github/workflows/called-required-workflow.yml
--- a/.github/workflows/called-required-workflow.yml
+++ b/.github/workflows/called-required-workflow.yml
@@ -10,13 +10,13 @@ jobs:
       - name: Always pass
         run: exit 0
 
-  job-always-fail:
-    name: Failing job
-    runs-on: ubuntu-latest
-    steps:
-     - name: Always fail
-       run: exit 1
-    
+#   job-always-fail:
+#     name: Failing job
+#     runs-on: ubuntu-latest
+#     steps:
+#      - name: Always fail
+#        run: exit 1
+#     
 #   job-to-be-skipped:
 #      if: false
 #      name: Skipped job
